# -*- coding: utf-8 -*-
"""MPLS_Vision_Bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d2lXtDWPIULMxpvHoUSDD5Muf9y0snTQ

# 🤖 MPLS Vision Bot

Este cuaderno permite ejecutar en Google Colab un bot de Telegram para validar automáticamente etiquetas de red enviadas como fotos por técnicos de campo.

### Incluye:
- OCR con EasyOCR
- Validación estructural (Ruta Completa o No Aplica)
- Mensajes detallados (válidos / inválidos)
- Menú interactivo persistente
- Preparado para Google Colab

## 🔧 Instalación de librerías
"""

!pip install python-telegram-bot --quiet
!pip install easyocr opencv-python-headless nest_asyncio --quiet

"""## 🔐 Token del bot"""

TOKEN = '8243499597:AAHhpezJxk8wFzkzZFzCEwer5eE1BEDSlyM'

"""## 🧠 Clase MPLSVisionValidator"""

VALID_COLORS = {
    "ROJ": "ROJO", "BLA": "BLANCO", "CAF": "CAFÉ", "VER": "VERDE", "NAR": "NARANJA",
    "AZU": "AZUL", "ROS": "ROSADO", "VIO": "VIOLETA", "GRI": "GRIS", "NEG": "NEGRO",
    "CEL": "CELESTE", "AMA": "AMARILLO"
}


class MPLSVisionValidator:

    def parse_and_validate(self, raw_text: str) -> dict:
        import re
        result = {"valid": False, "error": "", "type": "Desconocido"}

        try:
            text = raw_text.strip().replace("\n", "").replace("\r", "").replace("—", "-").replace("–", "-").replace("／", "/")

            # REGEX para Ruta No Aplica
            match_na = re.match(r"^(.*?)-(.+?)-(.+?)/N/A-(.+?)-(.+?)-(.+?)$", text, re.IGNORECASE)
            if match_na:
                ciudad, concentrador, estandar, ruta, caja, color = match_na.groups()
                result.update({
                    "type": "Ruta No Aplica",
                    "city": ciudad,
                    "node_concentrator": concentrador,
                    "node_standard": estandar,
                    "route": ruta,
                    "box_code": caja,
                    "color": color.upper(),
                    "color_name": VALID_COLORS.get(color.upper(), "Desconocido"),
                    "emoji": "📁"
                })
            else:
                # REGEX para Ruta Completa
                match_rc = re.match(r"^(.*?)-(.+?)-(.+?)/(.+?)-(.+?)-(.+?)-(.+?)$", text, re.IGNORECASE)
                if not match_rc:
                    result["error"] = "No coincide con ninguna estructura reconocida de etiqueta."
                    return result
                ciudad, concentrador, estandar, backup, ruta, caja, color = match_rc.groups()
                result.update({
                    "type": "Ruta Completa",
                    "city": ciudad,
                    "node_concentrator": concentrador,
                    "node_standard": estandar,
                    "node_backup": backup,
                    "route": ruta,
                    "box_code": caja,
                    "color": color.upper(),
                    "color_name": VALID_COLORS.get(color.upper(), "Desconocido"),
                    "emoji": "📦"
                })

            if result["color"] not in VALID_COLORS:
                result["error"] = f"Color inválido: {result['color']}."
                return result

            result["valid"] = True
            return result

        except Exception as e:
            result["error"] = f"Error al procesar la etiqueta: {str(e)}"
            return result

    def format_response(self, data: dict, ocr_text: str, confidence: float = None) -> str:
        from datetime import datetime
        now = datetime.now().strftime("%H:%M")
        lines = []

        if data.get("valid"):
            lines.append("PROCESANDO IMAGEN...")
            lines.append(f"✓ Texto extraído: {ocr_text}")
            lines.append(f"{data['emoji']} Código detectado: {ocr_text}")
            lines.append(f"📁 Tipo de ruta: {data['type']}")
            lines.append(f"🎨 Color buffer: {data['color_name'].upper()}")
            lines.append("✅ Estado: VÁLIDO")
            lines.append("")
            lines.append("DETALLES:")
            lines.append(f"• Ciudad: {data['city']}")
            lines.append(f"• Nodo Concentrador: {data['node_concentrator']}")
            lines.append(f"• Nodo Estándar: {data['node_standard']}")
            if data.get("node_backup"):
                lines.append(f"• Nodo Backup: {data['node_backup']}")
            lines.append(f"• Ruta: {data['route']}")
            lines.append(f"• Caja/Código: {data['box_code']}")
            lines.append(f"• Color: {data['color']} ({data['color_name']})")
        else:
            lines.append("PROCESANDO IMAGEN...")
            lines.append(f"✓ Texto extraído: {ocr_text}")
            lines.append(f"❌ Código detectado: {ocr_text}")
            lines.append(f"📁 Tipo de ruta: {data.get('type', 'No identificado')}")
            lines.append("❌ Estado: INVÁLIDO")
            lines.append("")
            lines.append("ERROR:")
            lines.append(data["error"])
            lines.append("")
            lines.append("RECOMENDACIONES:")
            lines.append("• Verifica la etiqueta físicamente.")
            lines.append("• Reintenta con mejor iluminación.")
            lines.append("• Colores válidos: ROJ, BLA, CAF, VER, NAR, AZU, ROS, VIO, GRI, NEG, CEL, AMA")

        lines.append(f"🕒 {now} - @mpls_vision_bot")
        if confidence:
            lines.append(f"📊 Confianza OCR: {int(confidence * 100)}%")

        return "\n".join(lines)

"""## ▶️ Inicio del bot Telegram"""

import nest_asyncio
nest_asyncio.apply()

from telegram import Update, ReplyKeyboardMarkup, ReplyKeyboardRemove
from telegram.ext import ApplicationBuilder, CommandHandler, MessageHandler, filters, ContextTypes
import cv2
import numpy as np
import easyocr

# Inicializar OCR y validador
validator = MPLSVisionValidator()
reader = easyocr.Reader(['es'], gpu=False)

# Función para crear el menú principal
def get_main_menu():
    return ReplyKeyboardMarkup(
        [["📷 Enviar Imagen"], ["ℹ️ Ayuda", "❌ Salir"]],
        resize_keyboard=True,
        one_time_keyboard=False
    )

# Comando /start
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    bienvenida = (
        "👋 *¡Hola! Bienvenido/a al MPLS Vision Bot*\n\n"
        "📷 Envíame una imagen de una etiqueta MPLS y validaré automáticamente:\n"
        "• Tipo de ruta (Completa o No Aplica)\n"
        "• Estado (VÁLIDO o INVÁLIDO)\n"
        "• Recomendaciones técnicas\n\n"
        "🚀 Usa el menú para interactuar con el bot o simplemente envía tu imagen."
    )

    await update.message.reply_text(
        bienvenida,
        parse_mode="Markdown",
        reply_markup=get_main_menu()
    )

# Comando /ayuda
async def ayuda(update: Update, context: ContextTypes.DEFAULT_TYPE):
    texto = (
        "ℹ️ *¿Cómo funciona este bot?*\n\n"
        "1. Envía una imagen clara de la etiqueta\n"
        "2. Extraigo y valido el texto usando OCR\n"
        "3. Te indico si la etiqueta es válida y por qué\n\n"
        "✅ Puedes enviar tantas imágenes como quieras\n"
        "❌ Usa el botón Salir para terminar la conversación"
    )

    await update.message.reply_text(
        texto,
        parse_mode="Markdown",
        reply_markup=get_main_menu()
    )

# Comando /salir
async def salir(update: Update, context: ContextTypes.DEFAULT_TYPE):
    despedida = "👋 *¡Gracias por usar el MPLS Vision Bot!*\n\nHasta la próxima."
    await update.message.reply_text(
        despedida,
        parse_mode="Markdown",
        reply_markup=ReplyKeyboardRemove()
    )

# Procesar imagen
async def handle_photo(update: Update, context: ContextTypes.DEFAULT_TYPE):
    try:
        # Mensaje de procesamiento
        processing_msg = await update.message.reply_text("⏳ *Procesando imagen...*", parse_mode="Markdown")

        photo = update.message.photo[-1]
        photo_file = await photo.get_file()
        img_bytes = await photo_file.download_as_bytearray()
        img = cv2.imdecode(np.frombuffer(img_bytes, np.uint8), cv2.IMREAD_COLOR)
        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        results = reader.readtext(img_rgb)
        ocr_text = ' '.join([text for (_, text, _) in results]).strip()
        confidence = sum([conf for (_, _, conf) in results]) / len(results) if results else 0

        result = validator.parse_and_validate(ocr_text)
        response_raw = validator.format_response(result, ocr_text, confidence)

        # Eliminar mensaje de procesamiento
        await processing_msg.delete()

        # Enviar resultado
        await update.message.reply_text(response_raw)

        # Preguntar si desea validar otra
        teclado = ReplyKeyboardMarkup(
            [["✅ Sí", "❌ No"]],
            resize_keyboard=True,
            one_time_keyboard=True
        )
        await update.message.reply_text(
            "¿Deseas validar otra imagen?",
            reply_markup=teclado
        )

    except Exception as e:
        error_msg = f"❌ *Error al procesar la imagen:*\n\n`{str(e)}`"
        await update.message.reply_text(error_msg, parse_mode="Markdown")

# Manejar respuesta del teclado personalizado
async def manejar_respuesta(update: Update, context: ContextTypes.DEFAULT_TYPE):
    texto = update.message.text

    if texto == "✅ Sí":
        await update.message.reply_text(
            "Perfecto 👌 Puedes enviarme la siguiente imagen.",
            reply_markup=get_main_menu()
        )
    elif texto == "❌ No":
        await salir(update, context)
    elif texto == "📷 Enviar Imagen":
        await update.message.reply_text(
            "📸 *Perfecto!*\n\nEnvía la imagen de la etiqueta MPLS que deseas validar.",
            parse_mode="Markdown"
        )
    elif texto == "ℹ️ Ayuda":
        await ayuda(update, context)
    elif texto == "❌ Salir":
        await salir(update, context)

# Construir app y agregar handlers
app = ApplicationBuilder().token(TOKEN).build()
app.add_handler(CommandHandler("start", start))
app.add_handler(CommandHandler("ayuda", ayuda))
app.add_handler(CommandHandler("salir", salir))
app.add_handler(MessageHandler(filters.PHOTO, handle_photo))
app.add_handler(MessageHandler(filters.TEXT & (~filters.COMMAND), manejar_respuesta))

await app.initialize()
await app.start()
print("🤖 Bot ejecutándose. Esperando imágenes y comandos...")
await app.updater.start_polling()